apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongoservices.saada.mongodb.operator
spec:
  group: saada.mongodb.operator
  names:
    kind: MongoService
    listKind: MongoServiceList
    plural: mongoservices
    singular: mongoservice
  scope: Namespaced
  version: v1alpha1
